#!/bin/bash
#BSUB -q gpuv100
#BSUB -J yoloTrain_noback
#BSUB -n 2
#BSUB -gpu "num=2:mode=exclusive_process"
#BSUB -W 24:00
#BSUB -R "rusage[mem=10GB]"
#BSUB -u sitan@dtu.dk
#BSUB -B
#BSUB -N
#BSUB -B
#BSUB -o logs/gpu-%J.out
#BSUB -e logs/gpu-%J.err

#bsub -R "select[gpu16gb]"

nvidia-smi
module load cuda/9.0
module load cudnn/v7.0.5-prod-cuda-9.0
module load opencv/3.2.0

cd darknet/
./darknet detector train ../cfg/fish_green.data ../cfg/yolov3-fish1.cfg ../darknet53.conv.74 -dont_show -map -gpus 0,1
