#!/bin/bash

module load python3/3.6.2 &>/dev/null
module load openblas/0.3.5 &>/dev/null

module load cuda/9.2 &>/dev/null
module load cudnn/v7.4.2.24-prod-cuda-9.2 &>/dev/null

# faiss depends on libomp and libstdc++
module load clang/8.0.0 &>/dev/null
module load gcc/7.4.0 &>/dev/null

python3 "$@"